name: Deploy to develop

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{secrets.DEV_ACCESS_TOKEN}}
      SUPABASE_PROJECT_ID: ${{secrets.DEV_PROJECT_ID}}
      SUPABASE_DB_PASSWORD: ${{secrets.DEV_DB_PASSWORD}}
      SUPABASE_CONNECTION_STRING: ${{secrets.DEV_CONNECTION_STRING}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Login into Supabase
        uses: supabase/setup-cli@v1
        with:
          version: 1.86.1 # Select here a supabase cli version

      - name: Deploy new migrations
        run: |
          updt_connection_string="${SUPABASE_CONNECTION_STRING/\[YOUR-PASSWORD\]/$SUPABASE_DB_PASSWORD}"
          supabase db push --include-all --db-url $updt_connection_string

      - name: Deploy Edge Functions
        run: |
          chmod +x ./deploy.sh
          bash ./deploy.sh development
