name: Deploy to prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{secrets.PROD_ACCESS_TOKEN}}
      SUPABASE_PROJECT_ID: ${{secrets.PROD_PROJECT_ID}}
      SUPABASE_DB_PASSWORD: ${{secrets.PROD_DB_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Login into Supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Deploy Edge Functions
        run: |
          chmod +x ./deploy.sh
          bash ./deploy.sh production

      - name: Db Push
        run: supabase db push --include-all